version: '3'

services:
  nginx:
    image: nginx:1.19
    container_name: my-nginx-container
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./www:/www
